/**
 * Reusable Prompt Builder for the AI Code Review System.
 * 
 * Centralizes prompt design, structuring instructions for analysis categories
 * (security, performance, logic, and maintainability) and enforcing
 * strict JSON response shapes to guarantee safe downstream ingestion.
 */

/**
 * Returns the centralized, highly descriptive system prompt guiding the LLM
 * through its Senior Software Engineer and Security Auditor review role.
 * 
 * @returns {string} System instruction set
 */
function buildSystemPrompt() {
  return `You are a world-class Senior Software Engineer and Security Auditor.
Your task is to review the code changes in a Pull Request.

Please analyze the provided pull request code changes across the following four core dimensions:
1. **Logic & Correctness**: Detect critical bugs, off-by-one errors, race conditions, type mismatches, and regression risks.
2. **Security**: Identify vulnerabilities (e.g., hardcoded secrets, injection, timing side-channels, insecure configurations, lack of sanitization).
3. **Performance**: Recommend optimizations for runtime complexity, memory footprints, database querying, network operations, and caching.
4. **Maintainability**: Review readability, module decoupling, testability, standard naming conventions, and documentation nitpicks (only if significant).

INSTRUCTIONS FOR PR LINE NUMBERS:
- The diff you will receive is custom-annotated with prefix headers.
- Each line is prefixed with its exact line number in the NEW modified file (e.g., "  42: + const x = 1;").
- For deleted lines, the prefix represents the line number in the OLD original file (marked with "-").
- When suggesting inline review comments, you MUST provide the exact line number of the change in the NEW file.
- If a comment references a deleted line, reference the nearest active context line in the NEW file.

STRICT JSON RESPONSE FORMAT:
Your output must be a single, valid JSON object matching the schema below.
Ensure you return strict JSON. Do not wrap your response in markdown code blocks (e.g., do not start with \`\`\`json).

RESPONSE SCHEMA:
{
  "summary": "A concise, high-level markdown summary of your overall PR review findings. Include positive feedback, primary concerns, and an overall assessment.",
  "comments": [
    {
      "path": "relative/file/path.js",
      "line": 42,
      "body": "Your detailed feedback and code recommendations. Explain the impact of the issue (e.g., security risk, performance hit), and provide a clear, actionable code snippet demonstrating the correct fix."
    }
  ]
}`;
}

/**
 * Compiles metadata and formatted diffs into a unified user prompt string.
 * 
 * @param {string} formattedDiff - Compact annotated code diff generated by formatDiff utility
 * @param {Object} prMetadata - Contextual PR information
 * @param {number} prMetadata.number - PR number
 * @param {string} prMetadata.title - PR title
 * @param {string} prMetadata.repository - Repository full name
 * @returns {string} Fully compiled user prompt
 */
function buildUserPrompt(formattedDiff, prMetadata) {
  const title = prMetadata.title || 'Untitled Pull Request';
  const repo = prMetadata.repository || 'unknown/repository';
  const prNum = prMetadata.number || 'unknown';

  return `Pull Request Title: "${title}"
Repository: ${repo}
PR Number: #${prNum}

Below are the file changes to review:
${formattedDiff}`;
}

module.exports = {
  buildSystemPrompt,
  buildUserPrompt
};
