const { OpenAI } = require('openai');
const config = require('../config');
const { buildSystemPrompt, buildUserPrompt } = require('../utils/promptBuilder');
const { cleanAndRepairJSON, sanitizeReviewPayload } = require('../utils/sanitizeJson');

// Helper sleep promise
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * AI Service for interfacing with LLMs via OpenRouter's OpenAI-compatible API.
 * 
 * Includes:
 *  1. Exponential Backoff Retry Engine (handles 429, 5xx, and network timeouts).
 *  2. Malformed JSON Generation Retries.
 *  3. Fallback Regex-based Parser to rescue raw text summaries upon retry exhaustions.
 */
class AiService {
  constructor() {
    const apiKey = config.OPENROUTER_API_KEY;

    this.model = process.env.OPENROUTER_MODEL || 'google/gemini-2.5-flash';
    this.client = null;

    if (!apiKey) {
      if (config.isProduction) {
        console.error('[ERROR] [AI Service] OPENROUTER_API_KEY is missing in production! Review requests will fail.');
      } else {
        console.warn('[WARN] [AI Service] OPENROUTER_API_KEY is not configured. Running in MOCK/DEV mode (simulated AI reviews).');
      }
    } else {
      this.client = new OpenAI({
        baseURL: 'https://openrouter.ai/api/v1',
        apiKey,
        defaultHeaders: {
          'HTTP-Referer': 'https://github.com/vishwastiwariii/pr-review-ai',
          'X-Title': 'PRReview.ai Agent',
        }
      });
      console.log(`[SUCCESS] [AI Service] OpenRouter client initialized. Model: ${this.model}`);
    }
  }

  /**
   * Submits formatted pull request code diffs to OpenRouter and returns structured,
   * line-by-line review comments and a global summary.
   * 
   * Leverages an exponential backoff retry loop and falls back to a regex-based plain text
   * parser if all structured retries are exhausted.
   * 
   * @param {string} formattedDiff - Compact annotated code diff generated by formatDiff utility
   * @param {Object} prMetadata - Parsed PR context (pr number, repository, title, etc.)
   * @returns {Promise<Object>} Structured review payload: { summary: string, comments: Array }
   */
  async generatePullRequestReview(formattedDiff, prMetadata) {
    const isMockMode = !this.client;

    console.log(`[INFO] [AI Service] Triggering AI code analysis for PR #${prMetadata.number} (${isMockMode ? 'MOCK' : 'LIVE'} mode)...`);

    if (isMockMode) {
      return this._generateMockReview(prMetadata);
    }

    const systemPrompt = buildSystemPrompt();
    const userPrompt = buildUserPrompt(formattedDiff, prMetadata);

    const maxAttempts = 3;
    let lastError = null;
    let lastRawResponseText = '';

    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      try {
        if (attempt > 1) {
          // Calculate delay with exponential backoff and small jitter (min 1s, max 4s)
          const backoffDelay = Math.min(1000 * Math.pow(2, attempt - 2) + Math.random() * 500, 4000);
          console.warn(`[WARN] [AI Service] Retry Attempt ${attempt}/${maxAttempts} inside pipeline... Sleeping for ${backoffDelay.toFixed(0)}ms...`);
          await sleep(backoffDelay);
        }

        console.log(`[INFO] [AI Service] Executing OpenRouter completion request (Attempt ${attempt}/${maxAttempts})...`);
        
        const response = await this.client.chat.completions.create({
          model: this.model,
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userPrompt }
          ],
          response_format: { type: 'json_object' },
          temperature: 0.2, // Low temperature for high deterministic accuracy
          max_tokens: 1500,  // Limit completion tokens to fit within credit boundaries
        });

        lastRawResponseText = response.choices[0].message.content || '';
        
        if (!lastRawResponseText) {
          throw new Error('Received an empty response completion from AI model.');
        }

        // Attempt cleaning, stack-braces closing, and deep truncation repair
        const parsedReview = cleanAndRepairJSON(lastRawResponseText);

        if (!parsedReview) {
          throw new Error('JSON parsing and structural repair failed.');
        }

        // Schema validation & type casting
        const sanitizedReview = sanitizeReviewPayload(parsedReview);
        
        console.log(`[SUCCESS] [AI Service] AI review generated and sanitized successfully on attempt ${attempt}`);
        return sanitizedReview;

      } catch (err) {
        lastError = err;
        
        // Inspect transient status categories
        const status = err.status || '';
        const isTransient = status === 429 || (status >= 500 && status <= 504) || err.message.includes('timeout') || err.message.includes('parsing');
        
        console.error(
          `[ERROR] [AI Service] Attempt ${attempt}/${maxAttempts} failed. ` +
          `Reason: ${err.message}${status ? ` (Status ${status})` : ''}`
        );

        if (!isTransient && attempt < maxAttempts) {
          console.warn(`[WARN] [AI Service] Fatal connection or rate error caught. Attempting graceful retry boundary regardless.`);
        }
      }
    }

    // --- All retries exhausted: Invoke Fallback Parser ---
    console.error(`[ERROR] [AI Service] All ${maxAttempts} review generation attempts failed. Invoking Fallback Parser.`);
    
    try {
      return this._parseFallbackReview(lastRawResponseText, prMetadata, lastError);
    } catch (fallbackErr) {
      console.error(`[ERROR] [AI Service] Fallback parser crashed: ${fallbackErr.message}`);
      
      // Ultimate absolute fallback to guarantee the PR orchestrator never crashes
      return {
        summary: `### 🤖 AI Pull Request Review (Pipeline Error)\n\nAn automated AI code review was triggered for pull request **#${prMetadata.number}**, but could not be completed successfully.\n\n**Details of failure:**\n- **Service error**: ${lastError ? lastError.message : 'Unknown generation exception'}\n- **Fallback error**: ${fallbackErr.message}\n\nPlease review the changed files manually in the GitHub Files tab.`,
        comments: []
      };
    }
  }

  /**
   * Safe Fallback Parser to extract review context from totally malformed or truncated AI strings,
   * guaranteeing that a structured review payload is always returned.
   * 
   * @private
   */
  _parseFallbackReview(rawText, prMetadata, originalError) {
    console.warn(`[WARN] [AI Service] Running Regex Recovery Parser on raw string (${rawText ? rawText.length : 0} chars)...`);
    
    const result = {
      summary: '',
      comments: []
    };

    if (!rawText || typeof rawText !== 'string' || rawText.trim().length === 0) {
      result.summary = `### 🤖 AI Pull Request Review (API Connection Error)\n\nAn automated AI code review was triggered for pull request **#${prMetadata.number}**, but could not be processed due to a transient API or credit constraint.\n\n**Details of failure:**\n- **Error**: ${originalError ? originalError.message : 'OpenRouter endpoint timed out or failed to return content.'}`;
      return result;
    }

    const cleanText = rawText.replace(/```json|```/g, '').trim();
    let summaryText = '';

    // Attempt 1: Extract summary key from raw JSON-like string via RegExp
    const summaryMatch = cleanText.match(/"summary"\s*:\s*"([\s\S]*?)"\s*,\s*"comments"/);
    if (summaryMatch) {
      summaryText = summaryMatch[1]
        .replace(/\\n/g, '\n')
        .replace(/\\"/g, '"')
        .replace(/\\t/g, '  ');
    } else {
      // Attempt 2: If we couldn't parse the key, grab up to first 500 chars as high-level summary
      summaryText = cleanText.substring(0, 500);
      if (cleanText.length > 500) {
        summaryText += '... (Truncated AI raw completion)';
      }
    }

    result.summary = `### 🤖 AI Review Summary (Fallback Recovery)\n\n${summaryText}\n\n` +
      `> [!WARNING]\n` +
      `> **AI Code Review Resiliency Notice**:\n` +
      `> The detailed line-by-line inline code recommendations could not be programmatically parsed due to API token truncation or malformed response structures.\n` +
      `> * **Original parse error**: ${originalError ? originalError.message : 'Unexpected JSON end'}\n` +
      `> * Please consult the pull request changed files page for full manual auditing.`;

    return result;
  }

  /**
   * Generates a mock review structure to support development and testing without active OpenRouter credits.
   * 
   * @private
   */
  _generateMockReview(prMetadata) {
    return new Promise((resolve) => {
      setTimeout(() => {
        const mockResponse = {
          summary: `### 🤖 AI Review Summary (Simulated)\n\nOverall, the code in pull request **#${prMetadata.number}** is well-structured and aligns with basic coding standards. I have analyzed the diff and identified a few opportunities for enhancements in error logging boundaries and environment variables schema validations.\n\n* **Design Pattern**: 🟢 Pass (Clean Modular Separation)\n* **Security Checks**: 🟡 Minor Concern (Ensure secrets are loaded dynamically)\n* **Performance**: 🟢 Pass (No execution bottlenecks)`,
          comments: [
            {
              path: 'server/src/server.js',
              line: 6,
              body: '*(AI Suggestion)*: Consider adding a dynamic config validation check here to ensure all core ports and tunnels are registered on server initialization.'
            },
            {
              path: 'server/src/routes/webhooks.js',
              line: 15,
              body: '*(AI Suggestion)*: Centralized middleware signature validations look solid. Adding telemetry tracking (e.g. execution duration) could improve diagnostic capabilities.'
            }
          ]
        };
        console.log(`[SUCCESS] [AI Service] Mock review generated successfully for PR #${prMetadata.number}`);
        resolve(mockResponse);
      }, 1000);
    });
  }
}

module.exports = new AiService();
