const { OpenAI } = require('openai');
const config = require('../config');
const { buildSystemPrompt, buildUserPrompt } = require('../utils/promptBuilder');

/**
 * AI Service for interfacing with LLMs via OpenRouter's OpenAI-compatible API.
 * 
 * Responsible for constructing system prompts, injecting custom diff structures,
 * generating structured JSON review objects, and providing failsafe development fallbacks.
 */
class AiService {
  constructor() {
    const apiKey = config.OPENROUTER_API_KEY;
    const isDev = config.isDevelopment;

    this.model = process.env.OPENROUTER_MODEL || 'google/gemini-2.5-flash';
    this.client = null;

    if (!apiKey) {
      if (config.isProduction) {
        console.error('[ERROR] [AI Service] OPENROUTER_API_KEY is missing in production! Review requests will fail.');
      } else {
        console.warn('[WARN] [AI Service] OPENROUTER_API_KEY is not configured. Running in MOCK/DEV mode (simulated AI reviews).');
      }
    } else {
      this.client = new OpenAI({
        baseURL: 'https://openrouter.ai/api/v1',
        apiKey,
        defaultHeaders: {
          'HTTP-Referer': 'https://github.com/vishwastiwariii/pr-review-ai',
          'X-Title': 'PRReview.ai Agent',
        }
      });
      console.log(`[SUCCESS] [AI Service] OpenRouter client initialized. Model: ${this.model}`);
    }
  }

  /**
   * Submits formatted pull request code diffs to OpenRouter and returns structured,
   * line-by-line review comments and a global summary.
   * 
   * @param {string} formattedDiff - Compact annotated code diff generated by formatDiff utility
   * @param {Object} prMetadata - Parsed PR context (pr number, repository, title, etc.)
   * @returns {Promise<Object>} Structured review payload: { summary: string, comments: Array<{ path, line, body }> }
   */
  async generatePullRequestReview(formattedDiff, prMetadata) {
    const isMockMode = !this.client;

    console.log(`[INFO] [AI Service] Triggering AI code analysis for PR #${prMetadata.number} (${isMockMode ? 'MOCK' : 'LIVE'} mode)...`);

    if (isMockMode) {
      return this._generateMockReview(prMetadata);
    }

    const systemPrompt = buildSystemPrompt();
    const userPrompt = buildUserPrompt(formattedDiff, prMetadata);

    try {
      const response = await this.client.chat.completions.create({
        model: this.model,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        // Request structured JSON response
        response_format: { type: 'json_object' },
        temperature: 0.2, // Low temperature for high deterministic accuracy
        max_tokens: 1500, // Limit maximum completion tokens to fit within basic credit boundaries
      });

      const responseText = response.choices[0].message.content.trim();
      const parsedReview = JSON.parse(responseText);

      console.log(`[SUCCESS] [AI Service] AI review generated successfully for PR #${prMetadata.number}`);
      return parsedReview;
    } catch (error) {
      console.error(`[ERROR] [AI Service] OpenRouter request failed: ${error.message}`);
      throw new Error(`AI review generation failed: ${error.message}`);
    }
  }

  /**
   * Generates a mock review structure to support development and testing without active OpenRouter credits.
   * 
   * @private
   */
  _generateMockReview(prMetadata) {
    return new Promise((resolve) => {
      setTimeout(() => {
        const mockResponse = {
          summary: `### 🤖 AI Review Summary (Simulated)\n\nOverall, the code in pull request **#${prMetadata.number}** is well-structured and aligns with basic coding standards. I have analyzed the diff and identified a few opportunities for enhancements in error logging boundaries and environment variables schema validations.\n\n* **Design Pattern**: 🟢 Pass (Clean Modular Separation)\n* **Security Checks**: 🟡 Minor Concern (Ensure secrets are loaded dynamically)\n* **Performance**: 🟢 Pass (No execution bottlenecks)`,
          comments: [
            {
              path: 'server/src/server.js',
              line: 6,
              body: '*(AI Suggestion)*: Consider adding a dynamic config validation check here to ensure all core ports and tunnels are registered on server initialization.'
            },
            {
              path: 'server/src/routes/webhooks.js',
              line: 15,
              body: '*(AI Suggestion)*: Centralized middleware signature validations look solid. Adding telemetry tracking (e.g. execution duration) could improve diagnostic capabilities.'
            }
          ]
        };
        console.log(`[SUCCESS] [AI Service] Mock review generated successfully for PR #${prMetadata.number}`);
        resolve(mockResponse);
      }, 1000);
    });
  }
}

module.exports = new AiService();
